#
# Copyright (c) 2021 Nitric Technologies Pty Ltd.
#
# This file is part of Nitric Python 3 SDK.
# See https://github.com/nitrictech/python-sdk for further info.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: nitric/proto/spark/v1/spark.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase


if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


@dataclass(eq=False, repr=False)
class SparkSubmitRequest(betterproto.Message):
    cluster_name: str = betterproto.string_field(1)
    job_jar_path: str = betterproto.string_field(2)
    arguments: List[str] = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class SparkSubmitResponse(betterproto.Message):
    job_id: str = betterproto.string_field(1)
    status: str = betterproto.string_field(2)


class SparkStub(betterproto.ServiceStub):
    async def submit(
        self,
        spark_submit_request: "SparkSubmitRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SparkSubmitResponse":
        return await self._unary_unary(
            "/nitric.proto.spark.v1.Spark/Submit",
            spark_submit_request,
            SparkSubmitResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class SparkBase(ServiceBase):
    async def submit(
        self, spark_submit_request: "SparkSubmitRequest"
    ) -> "SparkSubmitResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_submit(
        self, stream: "grpclib.server.Stream[SparkSubmitRequest, SparkSubmitResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.submit(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/nitric.proto.spark.v1.Spark/Submit": grpclib.const.Handler(
                self.__rpc_submit,
                grpclib.const.Cardinality.UNARY_UNARY,
                SparkSubmitRequest,
                SparkSubmitResponse,
            ),
        }
