# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: nitric/proto/spark/v1/spark.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase


if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


@dataclass(eq=False, repr=False)
class SparkExecuteRequest(betterproto.Message):
    cluster_name: str = betterproto.string_field(1)
    table_pattern: str = betterproto.string_field(2)
    instructions: List["SparkInstruction"] = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class SparkInstruction(betterproto.Message):
    filter: "FilterInstruction" = betterproto.message_field(1, group="action")
    map: "MapInstruction" = betterproto.message_field(2, group="action")
    sum: "SumInstruction" = betterproto.message_field(3, group="action")
    save: "SaveInstruction" = betterproto.message_field(4, group="action")
    group_by: "GroupByInstruction" = betterproto.message_field(5, group="action")
    map_to_state: "MapToStateInstruction" = betterproto.message_field(6, group="action")


@dataclass(eq=False, repr=False)
class FilterInstruction(betterproto.Message):
    column: str = betterproto.string_field(1)
    operator: str = betterproto.string_field(2)
    value: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class MapInstruction(betterproto.Message):
    column: str = betterproto.string_field(1)
    operator: str = betterproto.string_field(2)
    value: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class SumInstruction(betterproto.Message):
    column: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class SaveInstruction(betterproto.Message):
    target_table: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class GroupByInstruction(betterproto.Message):
    columns: List[str] = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class MapToStateInstruction(betterproto.Message):
    key_column: str = betterproto.string_field(1)
    state_name: str = betterproto.string_field(2)
    operation: str = betterproto.string_field(3)
    column: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class SparkExecuteResponse(betterproto.Message):
    value: float = betterproto.double_field(1)
    error: str = betterproto.string_field(2)


class SparkStub(betterproto.ServiceStub):
    async def execute(
        self,
        spark_execute_request: "SparkExecuteRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SparkExecuteResponse":
        return await self._unary_unary(
            "/nitric.proto.spark.v1.Spark/Execute",
            spark_execute_request,
            SparkExecuteResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class SparkBase(ServiceBase):
    async def execute(
        self, spark_execute_request: "SparkExecuteRequest"
    ) -> "SparkExecuteResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_execute(
        self, stream: "grpclib.server.Stream[SparkExecuteRequest, SparkExecuteResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.execute(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/nitric.proto.spark.v1.Spark/Execute": grpclib.const.Handler(
                self.__rpc_execute,
                grpclib.const.Cardinality.UNARY_UNARY,
                SparkExecuteRequest,
                SparkExecuteResponse,
            ),
        }
