# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: nitric/proto/analyticsservice/v1/analyticsservice.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    TYPE_CHECKING,
    Dict,
    List,
    Optional,
)

import betterproto
import grpclib
from betterproto.grpc.grpclib_server import ServiceBase


if TYPE_CHECKING:
    import grpclib.server
    from betterproto.grpc.grpclib_client import MetadataLike
    from grpclib.metadata import Deadline


class EnginePreference(betterproto.Enum):
    ENGINE_UNSPECIFIED = 0
    SPARK_STREAMING = 1
    SPARK_BATCH = 2
    MATERIALIZED_VIEW = 3


class PipelineMode(betterproto.Enum):
    PIPELINE_MODE_UNSPECIFIED = 0
    DATA = 1
    STATE = 2


class StateOperation(betterproto.Enum):
    STATE_OPERATION_UNSPECIFIED = 0
    REPLACE = 1
    INCREMENT = 2
    DECREMENT = 3
    MAXIMUM = 4
    MINIMUM = 5
    COLLECT = 6


class StreamOperator(betterproto.Enum):
    STREAM_OPERATOR_UNSPECIFIED = 0
    ISTREAM = 1
    """
    IStream — emit a tuple when it is INSERTED into the relation. A tuple is
    "inserted" when it appears for the first time, or when it re-enters after
    being absent (e.g. crossed a threshold). Spark streaming:
    outputMode("append") — only new rows per batch. Materialized view: triggers
    on INSERT events via CDC.
    """

    DSTREAM = 2
    """
    DStream — emit a tuple when it is DELETED from the relation. A tuple is
    "deleted" when it is retracted — a key is removed or a filter step
    eliminates it from the current state. Spark streaming: requires retraction
    tracking (append of tombstones). Materialized view: triggers on DELETE
    events via CDC.
    """

    RSTREAM = 3
    """
    RStream — emit the entire current relation at every evaluation. Produces a
    full snapshot on every micro-batch or refresh tick. Spark streaming:
    outputMode("complete") — full table every batch. Materialized view: full
    refresh on schedule.
    """


class LogicalOperator(betterproto.Enum):
    LOGICAL_OPERATOR_UNSPECIFIED = 0
    AND = 1
    OR = 2
    NOT = 3


@dataclass(eq=False, repr=False)
class SparkStreamingExecuteRequest(betterproto.Message):
    pipeline: "Pipeline" = betterproto.message_field(1)
    hints: "Hints" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class SparkStreamingExecuteResponse(betterproto.Message):
    query_id: str = betterproto.string_field(1)
    error: str = betterproto.string_field(2)
    """Non-empty if the pipeline was rejected or failed to start."""


@dataclass(eq=False, repr=False)
class SparkBatchExecuteRequest(betterproto.Message):
    pipeline: "Pipeline" = betterproto.message_field(1)
    hints: "BatchHints" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class BatchHints(betterproto.Message):
    partition_column: str = betterproto.string_field(1)
    adaptive_query: bool = betterproto.bool_field(2)
    shuffle_partitions: int = betterproto.int32_field(3)
    starting_offsets: str = betterproto.string_field(4)
    """
    For Kafka sources: read from earliest or latest offset. Default: earliest —
    batch reads full topic history.
    """


@dataclass(eq=False, repr=False)
class SparkBatchExecuteResponse(betterproto.Message):
    rows_written: int = betterproto.int64_field(1)
    """Number of rows written to the sink."""

    output_path: str = betterproto.string_field(2)
    """Path or table name where results were written."""

    error: str = betterproto.string_field(3)
    """Non-empty if the job failed."""


@dataclass(eq=False, repr=False)
class ExecuteRequest(betterproto.Message):
    pipeline: "Pipeline" = betterproto.message_field(1)
    """
    The logical pipeline to execute. Engine-agnostic. This is the only thing
    the client needs to think about.
    """

    hints: "Hints" = betterproto.message_field(2)
    """
    Optional execution hints. All fields are optional — the router uses
    sensible defaults when omitted. See Hints below for field-by-field
    documentation.
    """


@dataclass(eq=False, repr=False)
class Hints(betterproto.Message):
    engine: "EnginePreference" = betterproto.enum_field(1)
    watermarks: Dict[str, str] = betterproto.map_field(
        2, betterproto.TYPE_STRING, betterproto.TYPE_STRING
    )
    checkpoint_base: str = betterproto.string_field(3)
    shuffle_partitions: int = betterproto.int32_field(4)
    partition_column: str = betterproto.string_field(5)
    adaptive_query: bool = betterproto.bool_field(6)
    connection_name: str = betterproto.string_field(7)
    refresh_strategy: str = betterproto.string_field(8)
    refresh_schedule: str = betterproto.string_field(9)
    create_indexes: bool = betterproto.bool_field(10)
    starting_offsets: str = betterproto.string_field(11)


@dataclass(eq=False, repr=False)
class ExecuteResponse(betterproto.Message):
    engine_used: "EnginePreference" = betterproto.enum_field(1)
    job_id: str = betterproto.string_field(2)
    error: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class PlanResponse(betterproto.Message):
    selected_engine: "EnginePreference" = betterproto.enum_field(1)
    reason: str = betterproto.string_field(2)
    warnings: List[str] = betterproto.string_field(3)
    physical_plan: List["StepTranslation"] = betterproto.message_field(4)
    """
    Step-by-step translation of the logical pipeline into physical operations
    for the selected engine. Useful for understanding what the engine will do.
    Example for Spark streaming:   "Filter        → df.filter(col('value') >
    0.0)"   "MapToState    → df.groupBy('room_id').agg(last('temperature'))
    .outputMode('update')"   "Sink          →
    writeStream.format('kafka').option('topic', 'room-state')"
    """

    error: str = betterproto.string_field(5)
    """
    Non-empty if the pipeline is invalid and would be rejected by Execute. The
    pipeline will not execute until this is resolved.
    """


@dataclass(eq=False, repr=False)
class StepTranslation(betterproto.Message):
    """
    One entry in the physical plan — maps a logical step to its physical
    translation for the selected engine.
    """

    step_index: int = betterproto.int32_field(1)
    """Index of the step in pipeline.steps (zero-based)."""

    operation: str = betterproto.string_field(2)
    """
    Type of the logical operation. Example: "Filter", "MapToState", "Window"
    """

    physical_translation: str = betterproto.string_field(3)
    """
    How the selected engine will physically execute this step. Engine-specific
    string — for human consumption in Plan responses only.
    """

    mode_at_step: "PipelineMode" = betterproto.enum_field(4)
    """Mode active when this step executes (DATA or STATE)."""


@dataclass(eq=False, repr=False)
class Pipeline(betterproto.Message):
    name: str = betterproto.string_field(1)
    mode: "PipelineMode" = betterproto.enum_field(2)
    source: "Source" = betterproto.message_field(3)
    steps: List["Step"] = betterproto.message_field(4)
    sink: "Sink" = betterproto.message_field(5)


@dataclass(eq=False, repr=False)
class Source(betterproto.Message):
    stream: "StreamSource" = betterproto.message_field(1, group="origin")
    table: "TableSource" = betterproto.message_field(2, group="origin")


@dataclass(eq=False, repr=False)
class StreamSource(betterproto.Message):
    name: str = betterproto.string_field(1)
    """Logical name. Example: "temperature_readings"""


@dataclass(eq=False, repr=False)
class TableSource(betterproto.Message):
    name: str = betterproto.string_field(1)
    """Logical name. Example: "room_state"""

    format: str = betterproto.string_field(2)
    """
    Format hint for file-based sources: parquet, csv, delta, json. Ignored by
    database-backed engines.
    """


@dataclass(eq=False, repr=False)
class Sink(betterproto.Message):
    stream: "StreamSink" = betterproto.message_field(1, group="destination")
    table: "TableSink" = betterproto.message_field(2, group="destination")


@dataclass(eq=False, repr=False)
class StreamSink(betterproto.Message):
    name: str = betterproto.string_field(1)
    """Logical name resolved by engine adapter."""


@dataclass(eq=False, repr=False)
class TableSink(betterproto.Message):
    name: str = betterproto.string_field(1)
    format: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class Step(betterproto.Message):
    filter: "Filter" = betterproto.message_field(1, group="operation")
    project: "Project" = betterproto.message_field(2, group="operation")
    window: "Window" = betterproto.message_field(3, group="operation")
    aggregate: "Aggregate" = betterproto.message_field(4, group="operation")
    join: "Join" = betterproto.message_field(5, group="operation")
    map_to_state: "MapToState" = betterproto.message_field(6, group="operation")
    map_to_data: "MapToData" = betterproto.message_field(7, group="operation")


@dataclass(eq=False, repr=False)
class Filter(betterproto.Message):
    predicate: "Expression" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class Project(betterproto.Message):
    columns: List["ColumnExpr"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class Window(betterproto.Message):
    duration: str = betterproto.string_field(1)
    """Example: "10 minutes"""

    slide: str = betterproto.string_field(2)
    """
    Slide interval for sliding windows. Empty = tumbling window. Must be <=
    duration when set.
    """

    time_column: str = betterproto.string_field(3)
    """Timestamp column to use as event time."""


@dataclass(eq=False, repr=False)
class Aggregate(betterproto.Message):
    group_by: List[str] = betterproto.string_field(1)
    """Columns to group by."""

    aggs: List["AggExpr"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class AggExpr(betterproto.Message):
    output_name: str = betterproto.string_field(1)
    """Name of the output column."""

    function: str = betterproto.string_field(2)
    """
    Aggregation function — logical name translated per engine:   SUM   → SUM()
    COUNT → COUNT()    AVG   → AVG()      MAX   → MAX()      MIN   → MIN()
    LAST  → last value seen
    """

    column: str = betterproto.string_field(3)
    """Column to aggregate."""


@dataclass(eq=False, repr=False)
class Join(betterproto.Message):
    right_source: str = betterproto.string_field(1)
    left_key: str = betterproto.string_field(2)
    right_key: str = betterproto.string_field(3)
    join_type: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class MapToState(betterproto.Message):
    key_column: str = betterproto.string_field(1)
    """
    Column that uniquely identifies each state entry. One output row per
    distinct value.
    """

    value_column: str = betterproto.string_field(2)
    """Column whose value drives the state update."""

    operation: "StateOperation" = betterproto.enum_field(3)


@dataclass(eq=False, repr=False)
class MapToData(betterproto.Message):
    operator: "StreamOperator" = betterproto.enum_field(1)
    schedule: str = betterproto.string_field(2)
    """
    Cron expression for PERIODIC strategy. Example: "0 * * * *" — top of every
    hour
    """


@dataclass(eq=False, repr=False)
class Expression(betterproto.Message):
    comparison: "ComparisonExpr" = betterproto.message_field(1, group="expr")
    logical: "LogicalExpr" = betterproto.message_field(2, group="expr")
    function: "FunctionCallExpr" = betterproto.message_field(3, group="expr")
    column_ref: "ColumnRef" = betterproto.message_field(4, group="expr")
    literal: "Literal" = betterproto.message_field(5, group="expr")
    arithmetic: "ArithmeticExpr" = betterproto.message_field(6, group="expr")


@dataclass(eq=False, repr=False)
class ComparisonExpr(betterproto.Message):
    left: "Expression" = betterproto.message_field(1)
    operator: str = betterproto.string_field(2)
    right: "Expression" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class LogicalExpr(betterproto.Message):
    operator: "LogicalOperator" = betterproto.enum_field(1)
    operands: List["Expression"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class FunctionCallExpr(betterproto.Message):
    name: str = betterproto.string_field(1)
    args: List["Expression"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class ArithmeticExpr(betterproto.Message):
    left: "Expression" = betterproto.message_field(1)
    operator: str = betterproto.string_field(2)
    right: "Expression" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class ColumnRef(betterproto.Message):
    name: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class Literal(betterproto.Message):
    string_val: str = betterproto.string_field(1, group="value")
    double_val: float = betterproto.double_field(2, group="value")
    int_val: int = betterproto.int64_field(3, group="value")
    bool_val: bool = betterproto.bool_field(4, group="value")


@dataclass(eq=False, repr=False)
class ColumnExpr(betterproto.Message):
    input_column: str = betterproto.string_field(1)
    output_column: str = betterproto.string_field(2)
    transform: "Expression" = betterproto.message_field(3)


class AnalyticsServiceStub(betterproto.ServiceStub):
    async def execute(
        self,
        execute_request: "ExecuteRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "ExecuteResponse":
        return await self._unary_unary(
            "/nitric.proto.analyticsservice.v1.AnalyticsService/Execute",
            execute_request,
            ExecuteResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )

    async def plan(
        self,
        execute_request: "ExecuteRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "PlanResponse":
        return await self._unary_unary(
            "/nitric.proto.analyticsservice.v1.AnalyticsService/Plan",
            execute_request,
            PlanResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class SparkStreamingExecutionServiceStub(betterproto.ServiceStub):
    async def execute(
        self,
        spark_streaming_execute_request: "SparkStreamingExecuteRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SparkStreamingExecuteResponse":
        return await self._unary_unary(
            "/nitric.proto.analyticsservice.v1.SparkStreamingExecutionService/Execute",
            spark_streaming_execute_request,
            SparkStreamingExecuteResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class SparkBatchExecutionServiceStub(betterproto.ServiceStub):
    async def execute(
        self,
        spark_batch_execute_request: "SparkBatchExecuteRequest",
        *,
        timeout: Optional[float] = None,
        deadline: Optional["Deadline"] = None,
        metadata: Optional["MetadataLike"] = None
    ) -> "SparkBatchExecuteResponse":
        return await self._unary_unary(
            "/nitric.proto.analyticsservice.v1.SparkBatchExecutionService/Execute",
            spark_batch_execute_request,
            SparkBatchExecuteResponse,
            timeout=timeout,
            deadline=deadline,
            metadata=metadata,
        )


class AnalyticsServiceBase(ServiceBase):
    async def execute(self, execute_request: "ExecuteRequest") -> "ExecuteResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def plan(self, execute_request: "ExecuteRequest") -> "PlanResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_execute(
        self, stream: "grpclib.server.Stream[ExecuteRequest, ExecuteResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.execute(request)
        await stream.send_message(response)

    async def __rpc_plan(
        self, stream: "grpclib.server.Stream[ExecuteRequest, PlanResponse]"
    ) -> None:
        request = await stream.recv_message()
        response = await self.plan(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/nitric.proto.analyticsservice.v1.AnalyticsService/Execute": grpclib.const.Handler(
                self.__rpc_execute,
                grpclib.const.Cardinality.UNARY_UNARY,
                ExecuteRequest,
                ExecuteResponse,
            ),
            "/nitric.proto.analyticsservice.v1.AnalyticsService/Plan": grpclib.const.Handler(
                self.__rpc_plan,
                grpclib.const.Cardinality.UNARY_UNARY,
                ExecuteRequest,
                PlanResponse,
            ),
        }


class SparkStreamingExecutionServiceBase(ServiceBase):
    async def execute(
        self, spark_streaming_execute_request: "SparkStreamingExecuteRequest"
    ) -> "SparkStreamingExecuteResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_execute(
        self,
        stream: "grpclib.server.Stream[SparkStreamingExecuteRequest, SparkStreamingExecuteResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.execute(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/nitric.proto.analyticsservice.v1.SparkStreamingExecutionService/Execute": grpclib.const.Handler(
                self.__rpc_execute,
                grpclib.const.Cardinality.UNARY_UNARY,
                SparkStreamingExecuteRequest,
                SparkStreamingExecuteResponse,
            ),
        }


class SparkBatchExecutionServiceBase(ServiceBase):
    async def execute(
        self, spark_batch_execute_request: "SparkBatchExecuteRequest"
    ) -> "SparkBatchExecuteResponse":
        raise grpclib.GRPCError(grpclib.const.Status.UNIMPLEMENTED)

    async def __rpc_execute(
        self,
        stream: "grpclib.server.Stream[SparkBatchExecuteRequest, SparkBatchExecuteResponse]",
    ) -> None:
        request = await stream.recv_message()
        response = await self.execute(request)
        await stream.send_message(response)

    def __mapping__(self) -> Dict[str, grpclib.const.Handler]:
        return {
            "/nitric.proto.analyticsservice.v1.SparkBatchExecutionService/Execute": grpclib.const.Handler(
                self.__rpc_execute,
                grpclib.const.Cardinality.UNARY_UNARY,
                SparkBatchExecuteRequest,
                SparkBatchExecuteResponse,
            ),
        }
